version: '3.4'
    
services:
  redis-node1:
    container_name: redis-node1
    build:
      context: redis
    ports:
      - "7001:7001"
      - "17001:17001"
    restart: always
    # network_mode: host
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7001",--cluster-announce-ip,"192.168.66.12"]
  redis-node2:
    container_name: redis-node2
    build:
      context: redis
    ports:
      - "7002:7002"
      - "17002:17002"
    restart: always
    # network_mode: host
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7002",--cluster-announce-ip,"192.168.66.12"]
  redis-node3:
    container_name: redis-node3
    build:
      context: redis
    ports:
      - "7003:7003"
      - "17003:17003"
    restart: always
    # network_mode: host
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7003",--cluster-announce-ip,"192.168.66.12"]
  redis-node4:
    container_name: redis-node4
    build:
      context: redis
    ports:
      - "7004:7004"
      - "17004:17004"
    restart: always
    # network_mode: host
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7004",--cluster-announce-ip,"192.168.66.12"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node5:
    container_name: redis-node5
    build:
      context: redis
    ports:
      - "7005:7005"
      - "17005:17005"
    restart: always
    # network_mode: host
    entrypoint: [redis-server, /etc/redis/rediscluster.conf,--port,"7005",--cluster-announce-ip,"192.168.66.12"]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3 
  redis-node6:
    container_name: redis-node6
    build:
      context: redis
    ports:
      - "7006:7006"
      - "17006:17006"
    restart: always
    # network_mode: host
    entrypoint: [redis-server, /etc/redis/rediscluster.conf, --port,"7006", --cluster-announce-ip,"192.168.66.12"]    
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-cluster-creator:
    image: redis
    # network_mode: host
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create 192.168.66.12:7001 192.168.66.12:7002 192.168.66.12:7003 192.168.66.12:7004 192.168.66.12:7005 192.168.66.12:7006 --cluster-replicas 1']
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6